In [3]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input{font-family:Consolas; font-size:12pt;}
div.prompt {min width:70px;}
div#toc-wrapper {padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe {font-size:12px;}
</style>
"""))

<font size='6' color='red'>ch10. N차원 배열(Numpy 배열) 다루기</font>
# 4절 복사와 뷰
## 4.1 할당

In [19]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b=a

In [6]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 2012118169424, numpy.ndarray)

In [7]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 2012118169424, numpy.ndarray)

In [8]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [9]:
np.all(a==b)

True

In [13]:
b.shape = (3,4) #할당 받은 b의 shape

In [14]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 2012118169424, numpy.ndarray)

In [15]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 2012118169424, numpy.ndarray)

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 4.2 얕은 복사 : 뷰 (View)

In [18]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# 뷰의 경우 데이터는 놔두고 틀만 복사하기에 reshape과 같은 변수를 사용함면 데이터의 형태는 변하지만 동일한 데이터를 사용한다
c = a.view()

In [21]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
id(a), id(c)

(2012151927536, 2012173461968)

In [23]:
a == c

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [24]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
c[1, ::2] = 9 # 1행의 짝수번째 열 변경(9)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  9,  7,  9,  9,  9, 11])

## 4.3 깊은 복사

In [40]:
a = np.array([[5, 4, 13, 0],
            [99, 6, 16, 1],
            [20, 5, 14, 0],])
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [41]:
# 독립변수의 가지수가 복수면 변수를 대문자로 짓는다
#X = a[:, :-1] #슬라이싱이 될 때, 뷰가 반환된다 (얕은복사)
X = a[:, :-1].copy() # X = np.array(a[:,:-1], copy=True)와 동일 (깊은복사)
X

array([[ 5,  4, 13],
       [99,  6, 16],
       [20,  5, 14]])

In [42]:
X[:, 0] = -9
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [43]:
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절 고급인덱싱